#!/bin/sh
# this needs to live in /etc/network/if-pre-up.d/

/sbin/iptables-restore < /etc/iptables.firewall.rules
sbadmins-MacBook-Pro:ban-hammer michael.raeder$ cat block-cn-ru.sh 
#!/bin/sh

# Create the ipset list
ipset -N china hash:net

# remove any old list that might exist from previous runs of this script
rm cn.zone

# Pull the latest IP set for China
wget -P . http://www.ipdeny.com/ipblocks/data/countries/cn.zone
wget -P . http://www.ipdeny.com/ipblocks/data/countries/ru.zone

# Add each IP address from the downloaded list into the ipset 'china'
for i in $(cat /etc/cn.zone ); do ipset -A china $i; done

# Restore iptables
/sbin/iptables-restore < /etc/iptables.firewall.rules
